
import React from "react";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { 
  BarChart2, 
  BrainCircuit, 
  ClipboardCheck, 
  Database, 
  LineChart, 
  UploadCloud, 
  UserCog,
  ArrowRight
} from "lucide-react";
import FeatureCard from "@/components/FeatureCard";

const Features = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <NavBar />
      
      <main className="flex-grow">
        {/* Hero Section */}
        <section className="bg-secondary/30 py-16 md:py-24">
          <div className="container mx-auto px-4">
            <div className="max-w-3xl mx-auto text-center">
              <h1 className="text-4xl md:text-5xl font-bold mb-6 heading-gradient">Product Features</h1>
              <p className="text-lg text-muted-foreground mb-8">
                Explore the powerful features that make Employee Compass the leading 
                solution for predictive employee retention.
              </p>
            </div>
          </div>
        </section>

        {/* Main Features */}
        <section className="py-16">
          <div className="container mx-auto px-4 max-w-6xl">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold mb-4">Core Capabilities</h2>
              <p className="text-lg text-foreground/80 max-w-2xl mx-auto">
                Our platform combines powerful analytics with AI to help you understand, predict, and improve employee retention.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <FeatureCard 
                icon={<LineChart size={24} />}
                title="Predictive Analytics"
                description="Use machine learning to identify employees at risk of leaving before they make the decision to leave."
              />
              <FeatureCard 
                icon={<BrainCircuit size={24} />}
                title="AI-Powered Insights"
                description="Get personalized retention strategies generated by our advanced AI model for each at-risk employee."
              />
              <FeatureCard 
                icon={<ClipboardCheck size={24} />}
                title="Retention Planning"
                description="Create and track actionable retention plans based on data-driven recommendations."
              />
              <FeatureCard 
                icon={<UserCog size={24} />}
                title="Employee Profiles"
                description="Comprehensive view of each employee with risk assessment and personalized retention actions."
              />
              <FeatureCard 
                icon={<BarChart2 size={24} />}
                title="Interactive Dashboard"
                description="Visualize key metrics and trends with customizable charts and reports."
              />
              <FeatureCard 
                icon={<UploadCloud size={24} />}
                title="Data Integration"
                description="Easily upload and integrate with your existing HR systems and employee data."
              />
              <FeatureCard 
                icon={<Database size={24} />}
                title="Secure Data Storage"
                description="Enterprise-grade security to protect your sensitive employee information."
              />
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-16 bg-primary text-white">
          <div className="container mx-auto px-4 text-center">
            <h2 className="text-3xl font-bold mb-6">Ready to Get Started?</h2>
            <p className="text-xl mb-8 max-w-2xl mx-auto opacity-90">
              Join hundreds of companies using Employee Compass to reduce turnover and build stronger teams.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button asChild size="lg" variant="secondary" className="px-8 text-primary hover-scale">
                <Link to="/signup" className="flex items-center gap-2">
                  Get Started Today <ArrowRight size={16} />
                </Link>
              </Button>
              <Button asChild size="lg" variant="outline" className="bg-transparent border-white text-white hover:bg-white/10 hover-scale">
                <Link to="/contact">Contact Sales</Link>
              </Button>
            </div>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default Features;
