
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import FeatureCard from "@/components/FeatureCard";
import TestimonialCard from "@/components/TestimonialCard";
import StatsCard from "@/components/StatsCard";
import { ArrowRight, BarChart2, BrainCircuit, ClipboardCheck, Database, Lightbulb, LineChart, UserCog, Users } from "lucide-react";

const Index = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <NavBar />
      
      {/* Hero Section */}
      <section className="hero-gradient py-16 md:py-24 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="text-center lg:text-left">
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 heading-gradient">
                Predict and Prevent Employee Turnover
              </h1>
              <p className="text-lg md:text-xl text-foreground/80 mb-8 max-w-xl mx-auto lg:mx-0">
                Use data-driven insights and AI to identify at-risk employees and implement effective retention strategies.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                <Button asChild size="lg" className="text-md px-8">
                  <Link to="/signup">Get Started</Link>
                </Button>
                <Button asChild variant="outline" size="lg" className="text-md px-8">
                  <Link to="/dashboard">View Demo</Link>
                </Button>
              </div>
            </div>
            <div className="hidden lg:block">
              <div className="relative">
                <div className="absolute inset-0 bg-gradient-to-br from-primary/20 to-retention-500/20 rounded-xl"></div>
                <img 
                  src="https://images.unsplash.com/photo-1568992687947-868a62a9f521?q=80&w=3432&auto=format&fit=crop" 
                  alt="HR team analyzing data" 
                  className="rounded-xl shadow-xl w-full h-auto object-cover animate-float" 
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 bg-white">
        <div className="container mx-auto max-w-6xl px-4">
          <h2 className="text-3xl font-bold text-center mb-12">Transforming Employee Retention</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <StatsCard 
              icon={<Users size={20} />} 
              title="Average Retention Improvement" 
              value="24%" 
              trend={{ value: "5% vs. industry", positive: true }}
            />
            <StatsCard 
              icon={<Database size={20} />} 
              title="Employee Records Analyzed" 
              value="1.2M+"
            />
            <StatsCard 
              icon={<BarChart2 size={20} />} 
              title="Prediction Accuracy" 
              value="94.7%" 
              trend={{ value: "2.3% this quarter", positive: true }}
            />
            <StatsCard 
              icon={<Lightbulb size={20} />} 
              title="Custom AI Insights Generated" 
              value="10K+" 
            />
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-secondary/30 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">Key Features</h2>
            <p className="text-lg text-foreground/80 max-w-2xl mx-auto">
              Our platform combines powerful analytics with AI to help you understand, predict, and improve employee retention.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <FeatureCard 
              icon={<LineChart size={24} />}
              title="Predictive Analytics"
              description="Use machine learning to identify employees at risk of leaving before they make the decision to leave."
            />
            <FeatureCard 
              icon={<BrainCircuit size={24} />}
              title="AI-Powered Insights"
              description="Get personalized retention strategies generated by our advanced AI model for each at-risk employee."
            />
            <FeatureCard 
              icon={<ClipboardCheck size={24} />}
              title="Retention Planning"
              description="Create and track actionable retention plans based on data-driven recommendations."
            />
            <FeatureCard 
              icon={<UserCog size={24} />}
              title="Employee Profiles"
              description="Comprehensive view of each employee with risk assessment and personalized retention actions."
            />
            <FeatureCard 
              icon={<BarChart2 size={24} />}
              title="Interactive Dashboard"
              description="Visualize key metrics and trends with customizable charts and reports."
            />
            <FeatureCard 
              icon={<Database size={24} />}
              title="Data Integration"
              description="Easily upload and integrate with your existing HR systems and employee data."
            />
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-16 bg-white px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">What Our Clients Say</h2>
            <p className="text-lg text-foreground/80 max-w-2xl mx-auto">
              HR professionals are transforming their retention strategies with our platform.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <TestimonialCard 
              quote="Employee Compass has revolutionized how we approach retention. We've reduced turnover by 31% in just six months by implementing the AI-suggested strategies."
              author="Sarah Johnson"
              role="HR Director"
              company="TechGlobal Inc."
            />
            <TestimonialCard 
              quote="The predictive analytics are incredibly accurate. We were able to proactively address concerns with key team members before they became serious issues."
              author="Michael Chen"
              role="People Operations Manager"
              company="Innovate Solutions"
            />
            <TestimonialCard 
              quote="What impressed me most was how quickly we saw results. The dashboard made it easy to identify trends and take immediate action where needed."
              author="Jennifer Rodriguez"
              role="Chief People Officer"
              company="Growth Ventures"
            />
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-primary px-4">
        <div className="container mx-auto max-w-6xl text-center">
          <h2 className="text-3xl font-bold text-white mb-6">Ready to Improve Your Employee Retention?</h2>
          <p className="text-xl text-white/90 mb-8 max-w-2xl mx-auto">
            Join hundreds of companies using Employee Compass to reduce turnover and build stronger teams.
          </p>
          <Button asChild size="lg" variant="secondary" className="px-8 text-primary">
            <Link to="/signup" className="flex items-center gap-2">
              Get Started Today <ArrowRight size={16} />
            </Link>
          </Button>
        </div>
      </section>
      
      <Footer />
    </div>
  );
};

export default Index;
