// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjhuufopnnkjtslvwrjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqaHV1Zm9wbm5ranRzbHZ3cmp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTg4MjksImV4cCI6MjA1OTc5NDgyOX0.Ay7nhPY3Ty2lsWF-sQUZ6Q9zRca3Anfv_i3FCe7IHhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);